services:
  payment_app:
    build: .
    container_name: payment-service-app
    volumes:
      - ../payment-service:/var/www
    networks:
      - laravel-net
    depends_on:
      - payment_db
      - rabbitmq-payment

  payment_web:
    image: nginx:stable-alpine
    container_name: payment-service-nginx
    ports:
      - "8003:80"
    volumes:
      - ../payment-service:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - payment_app

  payment_db:
    image: mysql:8
    container_name: payment-service-db
    environment:
      MYSQL_DATABASE: payment_service
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - payment_db_data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq-payment:
    image: rabbitmq:management
    container_name: rabbitmq-payment
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true

volumes:
  payment_db_data:
