services:
    menu_app:
        build: .
        container_name: menu-service-app
        volumes:
            - ../menu-service:/var/www
            - ../menu-service/bootstrap/cache:/var/www/bootstrap/cache
        networks:
            - laravel-net
        depends_on:
            - menu_db
            - rabbitmq-menu

    menu_web:
        image: nginx:stable-alpine
        container_name: menu-service-nginx
        ports:
            - "8001:80"
        volumes:
            - ../menu-service:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-net
        depends_on:
            - menu_app

    menu_db:
        image: postgres
        container_name: menu-service-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: menu_service
        volumes:
            - menu_db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel-net
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres", "-d", "menu_service"]
            interval: 10s
            retries: 10
            start_period: 30s
            timeout: 5s
    hasura:
        image: hasura/graphql-engine:latest
        container_name: hasura
        ports:
            - "8080:8080"
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secret@menu_db:5432/menu_service
            HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
        networks:
            - laravel-net
        depends_on:
            - menu_db
        restart: always
        healthcheck:
            test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s


    rabbitmq-menu:
        image: rabbitmq:management
        container_name: rabbitmq-menu
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - laravel-net

networks:
    laravel-net:
        external: true

volumes:
    menu_db_data:
